package helper.xml;

@SuppressWarnings("SpellCheckingInspection")
public enum XML_ATTRIBUTE {
    CLASS, PROCESSED_FIELD_ID, BELONG, FIELD_NAME, VAR_ID, FIELD_ID, VARDETAIL_CLASS, VARDETAIL_TYPE, VARDETAIL_VAL, VARDETAIL_VALTYPE
}
